### ISSUE TITLE
 Serious perfomance issues with 5.1

### ISSUE THREAD

**Issue by jdloudon** [yuzoolcode/pulsecms-tracking#57] opened 2018-06-25 09:33 UTC
I posted about this on the forum and believe it to be a bug now. Sites are unusable on PC with MS IE11 and on Mac with Chrome.
Also on all Android devices with any browser.
It turns out that turning off GeoIP data for site stats on setting page fixes the issue.
Shame as this is a useful feature. Please have a looksee.

**Comment by ghost** [comment] 2018-06-25 23:56
This is strange as nothing has changed that would have affected this (from previous versions or BETA).

Can you send in your Debug info (Admin > Settings > Extend > Debug download ZIP) so we can see what is going on?

ZIP it and send via Dropbox link or something to the forum Private Message :)

**Comment by ghost** [comment] 2018-06-26 00:13
I can see there's discussion on this here:
https://forum.pulsecms.com/t/serious-perfomance-issues-with-5-1-in-chrome-on-mac/1076/7

Closing here as not a bug in Pulse but in the server setup which we can hopefully solve over in the forum :)

**Closed as completed by ghost** 2018-06-26 00:13 UTC
Labels: bug, needs testing
