### ISSUE TITLE
Navigation links on RW pages aren’t clickable

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#54] opened 2018-06-19 01:16 UTC
on this website - https://www.grandvilleeducationfoundation.org/

- I have Pulse 5.1 installed
- I updated the Pulse 5 Stacks 
-  I checked the "inline edit" setting on the P5 integration stack
- and republished everything
- I also purged all browser Caches, including the Cloudflare one

after I login to the Pulse dashboard, and then open the Home page in a new tab. 

- On all browsers I can "inline edit" the Home page BUT I can't get to any page other than the Home page... and if I manually type in the Url for other pages, they load, but no inline editor is available...
- I can still edit individual "blocks" through the Pulse dashboard, just not the inline editor

"Stats" are now working on the Dashboard, which is cool, but not the inline editor

**Comment by ghost** [comment] 2018-06-19 01:55
I'm guessing Safari will be the same behaviour - but sounds like a Cache issue.

But this needs looking into. Thanks for the report :)

**Comment by unluckytoe** [comment] 2018-06-19 02:00
I can confirm that I see the same issue with Foundry. Cleared all cache for both Safari and Firefox, cannot edit inline.

**Comment by jrondorf** [comment] 2018-06-19 05:26
I tested also with Foundry and Foundation, on Chrome, Firefox and Safari, and inline edit was possible.
Therefore, I need login information for your dashboard, as inline edit will only be activated if logged in.

If inline edit is available on one page, but not the other, check that all P5 integration stacks on all pages have this option enabled.

Switching pages with the inbuilt navigation bar when in inline edit is an issue in some themes and we are looking into that. Inline edit in RW is still a beta feature.

**Comment by unluckytoe** [comment] 2018-06-19 05:40
Just sent you an email with my information.

**Comment by jrondorf** [comment] 2018-06-19 06:01
Thanks, will check.

**Comment by ghost** [comment] 2018-06-19 08:59
Works for me in Foundation and Foundry also, with Chrome and Safari.
Make sure to enable "inline editing" in the Stacks 

@GRMacGeek - will be best to send in more info on that setup / RW project.

**Comment by jrondorf** [comment] 2018-06-19 09:41
@unluckytoe It seems that no PHPSESSID is generated on your RW page. This would explain why the RW page doesn't recognise the logged in user. Did you change something there in your php.ini file?

@yuzoolcode The following check fails / is false for his page:
`if (\pulsecore\acl_role\is_administrator() or \pulsecore\acl_role\is_editor() ) {`

**Comment by unluckytoe** [comment] 2018-06-19 13:28
Hi Jannis,

Here are the options that I have in my PHP.ini file:

allow_url_fopen = On
allow_url_include = On
display_errors = Off
enable_dl = Off
file_uploads = On
max_execution_time = 30
max_input_time = 60
max_input_vars = 1000
memory_limit = 32M
post_max_size = 8M
session.gc_maxlifetime = 1440
session.save_path = "/var/cpanel/php/sessions/ea-php72"
upload_max_filesize = 2M
zlib.output_compression = On

I don’t see an option for PHPSESSID unfortunately. 

Brian

**Comment by GRMacGeek** [comment] 2018-06-19 14:06
@yuzoolcode I sent you login info via message on the forum, let me know if you would like the Rapidweaver project file as well.

**Comment by ghost** [comment] 2018-06-19 23:07
@unluckytoe does your host allow sessions?

When you install Pulse (admin/install.php) is there any errors about sessions at the bottom of the install check?

You can use this:
https://www.pulsecms.com/resources/reqs.zip

Put that on the server to check it.

Thanks @GRMacGeek replied and seems to be working. Let's talk in there :)

**Comment by unluckytoe** [comment] 2018-06-20 00:44
I installed the reqs.php file and ran it, here are the results. No errors when I run the installer either.

Because of a prior error, I did a clean install of Pulse and again cleared all the caches, and still does not work.

<img width="548" alt="screen shot 2018-06-19 at 5 17 02 pm" src="https://user-images.githubusercontent.com/843360/41631252-73b357e0-73e8-11e8-892a-27ced343a73d.png">

**Comment by ghost** [comment] 2018-06-20 00:46
Does Pulse work fine for you on its own?
e.g. yourdomain.com/pulse/admin - you can login in, change settings and see the inline editing as it is?

So the error is with Pulse+RapidWeaver or just Pulse?

**Comment by unluckytoe** [comment] 2018-06-20 00:50
Yep, I can log into Pulse, change the blocks text (for example, I changed the text on the banner image to say “Hi Michael, how are you?”. When I refresh the page after save, works perfect. However, I still cannot see the inline editor.

It would appear so far that it’s integration with both items for my instance.

Brian

**Comment by unluckytoe** [comment] 2018-06-20 00:55
Here is the report from the installer:


Pulse CMS Diagnostic Tool

System Requirements

Basic system requirements are an apache server with at least PHP 5.6 installed.

Server Type: Apache
PHP Version: 7.2.6
File Uploads: On
Safe Mode: Off
Magic Quotes: Off
GD Support: On	
Zip Extension: On

Permissions Check

Folders should have at least 755 and files 644 permissions, if the group is the same as the Apache web server. For example, if apache is running as the group www-data, then these files should be readable and writable by the www-group. For directories it should be readable, writable and executable by the www-group.

Folders should have at least 777 and files 666 permissions, if the web server group cant be determined

Other files and folders should be readable by the web server otherwise.

root directory - 0755
content - 0755
content/blocks - 0755
content/blog - 0755
content/media - 0755
content/pages - 0755
pulsecore/storage - 0755
pulsecore/storage/cache - 0755
pulsecore/storage/log - 0755
pulsecore/storage/config.json - 0666
pulsecore/vendor/browscap/browscap-php/resources - 0755
config.php - 0666

Path Setting

This is where Pulse is installed. If you installed Pulse in the root, it should should a blank space. If you are using Pulse inside a sub-folder, it should be set as "/sub".

Path Name: " /pulse"

.Htaccess Check

The .htaccess file is required for Pulse to work properly. If the file is missing, use the sample.htaccess file. Just remove the sample part and place it in the app root along with the index.php and config.php files.

The .htaccess file exists.

.htaccess file permissions 0666

Session Handling

If sessions are not working properly, it can cause problems with logging in and viewing blocks, etc.

Your hosting supports sessions

**Comment by jrondorf** [comment] 2018-06-20 06:00
@unluckytoe 
I still see no session on https://deafgoats.com/ when opening a new browser. This is required.
Could you please send me the generated deafgoats.com/index.php file ?

**Comment by unluckytoe** [comment] 2018-06-20 06:20
Here you go.

**Comment by jrondorf** [comment] 2018-06-20 07:02
Nothing received. Please send to my email address: https://instacks.com/contact/

**Comment by unluckytoe** [comment] 2018-06-20 07:03
Message sent

**Comment by jrondorf** [comment] 2018-06-20 07:23
Thanks, generated index.php looks fine and opens a session right at the start, which doesn't reflect in the browser.

**Comment by unluckytoe** [comment] 2018-06-20 07:25
So what could that mean?

**Comment by unluckytoe** [comment] 2018-06-20 07:49
Got it working. It would appear that when using Chillidog Hosting that you have to put the php.ini file inside the pulse directory.

Brian

**Comment by jrondorf** [comment] 2018-06-20 08:47
@unluckytoe Great to hear that!

**Comment by jrondorf** [comment] 2018-06-20 14:00
Remaining issue: Navigation links on RW pages aren’t clickable. We’ll look into this. 

Thanks guys for your feedback.

**Comment by jrondorf** [comment] 2019-01-21 11:08
https://github.com/yuzoolcode/pulsecms-tracking/issues/54

**Comment by jrondorf** [comment] 2019-01-21 19:58
Fixed with Pulse Stack 5.2.2

A new stack setting "Global Inline Edit" is introduced. Remove the checkbox for Foundation and Foundry, and add an "P5 Inline Edit" Stack to the page. This acts as container for inline editable content. Only add into this area your content and not the navigation bar.

All other themes, which have an inbuilt navigation bar (like default themes or Blankstrap) will work with "Global Inline Edit" checked and no dedicated "P5 Inline Edit" Stack.

Test project: https://instacks.com/pulsecmsstack/tutorial/#testproject

![2019-01-21_20-54-40](https://user-images.githubusercontent.com/2099795/51496212-251b0e80-1dbf-11e9-9f2e-6f1c6ed23ea7.png)

**Closed as completed by jrondorf** 2019-01-21 19:58 UTC
Labels: bug

**Comment by GRMacGeek** [comment] 2019-01-22 14:14
I can't get this to work in Foundation... 

- Inline edit worked before this update, now can't get it to work at all
- and until Rapidweaver 8.1 comes out, your new "test projects" can't be opened...

**Comment by ghost** [comment] 2019-01-22 14:17
> Inline edit worked before this update, now can't get it to work at all

Not with Foundation right?

> and until Rapidweaver 8.1 comes out, your new "test projects" can't be opened...

Yes this is something Jannis mentioned in the forums. It was an oversight by Realmac as they didn't tell anyone this would happen. 5.1 should be out in a matter of days..

**Comment by GRMacGeek** [comment] 2019-01-22 14:24
Yeah, building a new Rapidweaver/Foundation/Pulse site [here](http://99.198.97.170/~diemerru1/). 

Starting to add the Pulse  stacks now on pages [like this one](http://99.198.97.170/~diemerru1/triple-crown/) (the "test 1" is a Pulse block) but inline edit no longer works

- tried everything I could think of, "global edit" checked and unchecked
- put the "inline edit" stack around everything (except the nav), and just around the individual "Pulse Block" stack

Nothing. No pink boxes after I login to Pulse. 

- They were there before this update to the Pulse Stacks. Maybe because I am not on Rapidweaver 8.1? 

btw - I had to redownload the updated "Pulse Stacks" from Paddle. the Rapidweaver updater didn't add the new "inline stack"

**Comment by jrondorf** [comment] 2019-01-22 14:35
Please send me your project as zipped archive.

**Comment by jrondorf** [comment] 2019-01-22 14:39
Integrated update works for me reproduceable.

You **always** have to restart RW after integrated Stack updates have been performed.

**Comment by GRMacGeek** [comment] 2019-01-22 14:40
@jrondorf I messaged you a download link through the "Pulse Forums"
* Starting to add "Pulse stacks" to the "Triple Crown" page
